In [2]:
import numpy as np
arr = np.array([[1,2,4,5,6],[7,3,4,4,5]])
print(arr)
print(arr.shape)

[[1 2 4 5 6]
 [7 3 4 4 5]]
(2, 5)


In [3]:
arr = np.array([1,36])
print(arr.shape)

(2,)


In [8]:
arr = np.array([[[1,2,4,5,6],[7,3,4,4,5],[84,3,2,6,45]]])
print(arr.shape)

(1, 3, 5)


In [9]:
arr = np.array([[[1,3],[4,5]],[[3,4],[7,8]]])
print(arr.shape)

(2, 2, 2)


In [11]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_arr = arr.reshape(4,3)
print(new_arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [12]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_arr = arr.reshape(2,3,2)
print(new_arr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [13]:
arr = np.array([[1,2,4],[4,5,6]])
new_arr = arr.reshape(-1)
print(new_arr)

[1 2 4 4 5 6]


In [18]:
arr = np.array([[1,2,3,4],[1,2,3,4]])
new_arr = arr[:,np.newaxis]
print(new_arr)

[[[1 2 3 4]]

 [[1 2 3 4]]]


In [19]:
arr1 = np.array([1,2,3])
arr2 = np.array([2,3,4])
result = np.concatenate((arr1,arr2))
print(result)

[1 2 3 2 3 4]


In [20]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[4,5]])
result = np.concatenate((arr1,arr2), axis =0)
print(result)

[[1 2]
 [3 4]
 [4 5]]


In [24]:

arr3 = np.array([[7],[8]])
result = np.concatenate((arr1,arr3), axis =1)
print(result)

[[1 2 7]
 [3 4 8]]


In [27]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
result = np.hstack((arr1,arr2))
print(result)

[1 2 3 4 5 6]


In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
result = np.vstack((arr1,arr2))
print(result)

[[[1 4]
  [2 5]
  [3 6]]]


In [30]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
result = np.dstack((arr1,arr2))
print(result)

[[[1 4]
  [2 5]
  [3 6]]]


In [33]:
arr = np.array([1,2,3,4])
new_arr = np.array_split(arr,3)
print(new_arr)

[array([1, 2]), array([3]), array([4])]


In [41]:
arr1 = np.array([[1,2],[3,4],[5,6]])
new_arr= np.array_split(arr1,3,axis =1)
print(new_arr)

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int32)]


In [39]:
arr = np.array([1,2,3,4,5,6])
indiced = arr[np.where(arr>4)]
print(indiced)


[5 6]


In [40]:
arr = np.array([12,45,67,32,353,211,3])
sorted_arr= np.sort(arr)
print(sorted_arr)

[  3  12  32  45  67 211 353]
