In [2]:
#Data types
import numpy as np
arr = np.array([1,2,3,4,5,6],dtype = 'i')
print(arr.dtype)

int32


In [3]:
import numpy as np
arr = np.array([1.2,4.2,6.4],dtype = 'f')
print(arr.dtype)

float32


In [6]:
import numpy as np
arr = np.array([True,False,True],dtype = 'bool')
print(arr.dtype)

bool


In [9]:
arr2 = np.array(['apple','banana','cherry'])
print(arr2.dtype)

<U6


In [12]:
arr_s = np.array([1,2,3,4,5],dtype = 'S')
print(arr_s)
print(arr_s.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [18]:
arr_date = np.array(['2024-01-01','2023-01-01','2022-01-01'],dtype ='datetime64')
print(arr_date)
print(arr_date.dtype)

['2024-01-01' '2023-01-01' '2022-01-01']
datetime64[D]


In [20]:
# Copy and View:
import numpy as np
arr = np.array([10,20,30,40,50])
copy_arr = arr.copy()
arr[0] = 100
print(arr)
print(copy_arr)

[100  20  30  40  50]
[10 20 30 40 50]


In [22]:
arr = np.array([10,20,30,40,50])
view_arr = arr.view()
arr[0] = 200
print(arr)
print(view_arr)

[200  20  30  40  50]
[200  20  30  40  50]


In [24]:
arr = np.array([10,20,30,40,50])
view_arr = arr.view()
view_arr[1] = 200
print(arr)
print(view_arr)

[ 10 200  30  40  50]
[ 10 200  30  40  50]


In [25]:
#Shallow Copy 
import numpy as np
arr = np.array([10,20,30,40,50])
arr_shallow = arr
arr[0] = 100
print(arr)
print(arr_shallow)


[100  20  30  40  50]
[100  20  30  40  50]


In [26]:
arr = np.array([10,20,30,40,50])
arr_shallow = arr.view()
arr[1] = 200
print(arr)
print(arr_shallow)

[ 10 200  30  40  50]
[ 10 200  30  40  50]


In [27]:
arr = np.array([10,20,30,40,50])
arr_deep = arr.copy()
arr[1] = 200
print(arr)
print(arr_deep)

[ 10 200  30  40  50]
[10 20 30 40 50]
