In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [2]:
print(np.__version__)

1.26.4


In [ ]:
arr2 = np.array([[1,2],[3,4],[5,6]])
print(arr2)


[[1 2]
 [3 4]
 [5 6]]


In [4]:
arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [5]:
arr_22 = np.zeros((3,4))
print(arr_22)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
arr = np.ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [8]:
arr_22 = np.ones((3,4))
print(arr_22)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [14]:
arr = np.arange(0,100,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [15]:
arr = np.arange(0,100,0.5)
print(arr)

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5
 14.  14.5 15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5 20.  20.5
 21.  21.5 22.  22.5 23.  23.5 24.  24.5 25.  25.5 26.  26.5 27.  27.5
 28.  28.5 29.  29.5 30.  30.5 31.  31.5 32.  32.5 33.  33.5 34.  34.5
 35.  35.5 36.  36.5 37.  37.5 38.  38.5 39.  39.5 40.  40.5 41.  41.5
 42.  42.5 43.  43.5 44.  44.5 45.  45.5 46.  46.5 47.  47.5 48.  48.5
 49.  49.5 50.  50.5 51.  51.5 52.  52.5 53.  53.5 54.  54.5 55.  55.5
 56.  56.5 57.  57.5 58.  58.5 59.  59.5 60.  60.5 61.  61.5 62.  62.5
 63.  63.5 64.  64.5 65.  65.5 66.  66.5 67.  67.5 68.  68.5 69.  69.5
 70.  70.5 71.  71.5 72.  72.5 73.  73.5 74.  74.5 75.  75.5 76.  76.5
 77.  77.5 78.  78.5 79.  79.5 80.  80.5 81.  81.5 82.  82.5 83.  83.5
 84.  84.5 85.  85.5 86.  86.5 87.  87.5 88.  88.5 89.  89.5 90.  90.5
 91.  91.5 92.  92.5 93.  93.5 94.  94.5 95.  95.5 96.  96.5 97.  97.5
 98.  

In [17]:
identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
random_arr = np.random.randint(10,40,5)
print(random_arr)

0


In [ ]:
#Random value between 0 to 1
random_arr = np.random.rand(5)
print(random_arr)

[0.89871811 0.66948287 0.7813632  0.87390042 0.94330826]


In [36]:
#Reshaping array
arr = np.arange(6)
reshaped = arr.reshape(2,3)
print(reshaped)

[[0 1 2]
 [3 4 5]]


In [37]:
# Indexing:
arr = np.array([28,38,36,78,83])
print(arr[2])

36


In [49]:
arr = np.array([28,38,36,78,83])
indices = [0,2,4]
print(arr[indices])

[28 36 83]


In [38]:
arr_2d = np.array([[1,2,3],[7,9,0],[8,4,2]])
print(arr_2d[2,1])

4


In [43]:
arr = np.array([1,2,4,5,6,77,86,32])
print(arr[3:6])
print(arr[1:4])

[ 5  6 77]
[2 4 5]


In [48]:
arr_2d = np.array([[1,2,3],[7,9,0],[8,4,2]])
print(arr_2d[1,1])
print(arr_2d[0:2,1:3])

9
[[2 3]
 [9 0]]


In [ ]:
arr_2d = np.array([[1,2,3],[7,9,0],[8,4,2]])
print(arr_2d[[0,2],[1,2]])

[2 2]
